### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by salabim** [PaLora16/RecursiveDecorators#1]
Nice code!

I don't see why the AbstractInvoice class has to inherit from ABC.
And why the modify_invoice_contents function in AbstractInvoice has to be decorated with abstractmethod.
It works equally well without:

class AbstractInvoice():
    def __init__(self, invoice=None):
        self._invoice = invoice
        self._item = None

    def __call__(self, items: List[InvoiceItem]):
        self._items = items
        if self._invoice:
           self._invoice(items)
        self.modify_invoice_content()

    def modify_invoice_content(self) -> None:
        pass

I don't this the __call__ should return anything as the invoice_contents list is changed anyway.
So the end of the code could read then
    c(invoice_items)
    print("Modified invoice:")
    print(invoice_items)
, I think.

Finally, it is unclear to me why you are using the walrus operator to assign to an unused variable _. This would work as well:
        if sum(item.price * item.quantity for item in self._items) > 30:

**Comment by PaLora16** [comment]
As long as the class is marked as abstract, every derived class must follow the prescribed protocol, otherwise an error occurs. It's not about functionality, but safety for future extensions. Walrus assignment is useless here, you're right. A function that does not return value means that there is an unnecessary tight coupling to the inner function implementation. Any changes in the inner implementation would be notified to the client.

**Comment by salabim** [comment]
Ok.
I just don't get your argument of returning the items.
You are changing the given list anyway (actually an implementation detail as you indicate).
It's a little bit like the sort builtin. That sorts the list (or whatever) but returns None.

**Comment by PaLora16** [comment]
Well, it has to do with programming style. Indefinitely, we can argue about returning value and consuming internal object status. For example, in pure functional programming, every function should be stateless (except for holding inner status), which means the invoker should not depend on the inner state of its callee. Python is not a typical representation of functional programming, but I prefer clear input-black box-output as a preferred style.

**Comment by salabim** [comment]
Ok.
